# Generated by Django 2.0.1 on 2018-02-01 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_house_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='crop_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='green_house_management.Crop'),
        ),
    ]
