# Generated by Django 2.0.1 on 2018-02-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_house_management', '0003_auto_20180201_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='row',
            field=models.PositiveIntegerField(),
        ),
    ]
