# Generated by Django 2.0.1 on 2018-02-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_house_management', '0004_auto_20180201_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotsetting',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='green_house_management.Media'),
        ),
    ]
