# Generated by Django 2.0.1 on 2018-02-03 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_house_management', '0007_auto_20180201_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotsetting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='plotdevice',
            unique_together={('plot', 'device')},
        ),
    ]
