# Generated by Django 2.0.1 on 2018-02-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_house_management', '0009_auto_20180203_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotsetting',
            name='plot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='green_house_management.Plot'),
        ),
    ]
