# Generated by Django 2.0.1 on 2018-02-03 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_house_management', '0010_auto_20180203_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotsetting',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_house_management.Plot', unique=True),
        ),
    ]
