# Generated by Django 2.0.1 on 2018-02-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_house_management', '0012_auto_20180203_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorinformation',
            old_name='created',
            new_name='measurement_time',
        ),
        migrations.RenameField(
            model_name='sensorinformation',
            old_name='temparature',
            new_name='temp',
        ),
        migrations.RemoveField(
            model_name='sensorinformation',
            name='device',
        ),
        migrations.AddField(
            model_name='sensorinformation',
            name='serial',
            field=models.CharField(default='Device_Serial_Missing', max_length=30),
        ),
    ]
